import fs from 'node:fs';
import path from 'node:path';

const qrcodeRoot = '/home/zeki/projects/ztools/node_modules/qrcode/lib';
const dijkstraFile = '/home/zeki/projects/ztools/node_modules/dijkstrajs/dijkstra.js';
const licenseFile = '/home/zeki/projects/ztools/node_modules/qrcode/license';
const outFile = new URL('../public/vendor/qrcode.js', import.meta.url);

const modules = new Map();

function resolveRequire(fromFile, req) {
  let target = path.resolve(path.dirname(fromFile), req);
  if (!target.endsWith('.js')) {
    if (fs.existsSync(`${target}.js`)) target = `${target}.js`;
    else if (fs.existsSync(path.join(target, 'index.js'))) target = path.join(target, 'index.js');
  }
  return target;
}

function load(file, id) {
  if (modules.has(id)) return;
  let code = fs.readFileSync(file, 'utf8');
  code = code.replace(/require\(\s*['"]([^'"]+)['"]\s*\)/g, (match, req) => {
    if (req === 'dijkstrajs') {
      load(dijkstraFile, 'dijkstrajs');
      return `__require("dijkstrajs")`;
    }
    if (!req.startsWith('.')) {
      throw new Error(`Unsupported external require ${req} in ${file}`);
    }
    const target = resolveRequire(file, req);
    const targetId = path
      .relative(path.dirname(qrcodeRoot), target)
      .replace(/\\/g, '/')
      .replace(/\.js$/, '');
    load(target, targetId);
    return `__require(${JSON.stringify(targetId)})`;
  });
  modules.set(id, { code });
}

load(path.join(qrcodeRoot, 'browser.js'), 'qrcode/browser');

const license = fs.readFileSync(licenseFile, 'utf8').trim();
const parts = [];
parts.push('/* Vendored node-qrcode 1.5.4 + dijkstrajs (MIT). Generated by scripts/vendor-qrcode.mjs */');
parts.push(`/*\n${license}\n*/`);
parts.push('(function (global) {');
parts.push("'use strict';");
parts.push('var __defs = Object.create(null);');
parts.push('var __cache = Object.create(null);');
parts.push('function __require(id) {');
parts.push('  if (__cache[id]) return __cache[id].exports;');
parts.push("  if (!__defs[id]) throw new Error('Missing module ' + id);");
parts.push('  var module = { exports: {} };');
parts.push('  __cache[id] = module;');
parts.push('  __defs[id](module, module.exports, __require);');
parts.push('  return module.exports;');
parts.push('}');

for (const [id, mod] of modules) {
  parts.push(`__defs[${JSON.stringify(id)}] = function (module, exports, __require) {`);
  parts.push(mod.code);
  parts.push('};');
}

parts.push('var QRCode = __require("qrcode/browser");');
parts.push('global.QRCode = QRCode;');
parts.push('})(typeof window !== "undefined" ? window : globalThis);');
parts.push('');

fs.mkdirSync(path.dirname(fileURLToPathSafe(outFile)), { recursive: true });
fs.writeFileSync(fileURLToPathSafe(outFile), parts.join('\n'));

function fileURLToPathSafe(url) {
  return url.pathname;
}

console.log(`Wrote ${fileURLToPathSafe(outFile)} (${modules.size} modules)`);
